### PR TITLE
Flesh out regions for installer survey

### PR DESCRIPTION
**Pull request by mjturek**
Based on UPI docs [0] and IBM Cloud docs [1]

[0] https://github.com/ocp-power-automation/ocp4-upi-powervs/blob/master/docs/var.tfvars-doc.md
[1] https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server&locale=en#creating-service

### CODE REVIEW

**Comment by mjturek** [comment]
I included zone information even though we don't currently use it in the terraform as the installer still asks for zone

**Comment by clnperez** [comment]
LGTM

**Comment by clnperez** [comment]
Actually I would like to confirm the region we're using primarily to test. I think I've been using eu-gb for the region, but you've got lon. Maybe I haven't been using eu-gb? :D

**Comment by mjturek** [comment]
huh I've been using 'lon'!

**Comment by clnperez** [comment]
ok, yah that's right. thanks for confirming!

**Pull request merged**
