### PR TITLE
Pare down types and associated tests

### PR DESCRIPTION
**Pull request by mjturek**
Closes https://issues.redhat.com/browse/MULTIARCH-2014

### CODE REVIEW

**Comment by mjturek** [comment]
This should bring us back to the way platform and machinepools were in the upstream commit. The worker and master tests are removed as they were failing and no other platform seems to have their own tests there.

**Comment by mjturek** [comment]
haven't gotten workers to come up with this patch, need to make sure I didn't miss anything

**Comment by mjturek** [comment]
I'm having trouble getting workers to come up even without this patch. I'd appreciate if someone could try to deploy with this

**Comment by mjturek** [comment]
got workers to spawn with this patch. I think it's good to review

**Comment by clnperez** [comment]
LGTM

**Pull request merged**
