### PR TITLE
Rearrange TF modules into stages; "cluster" & "post-install"

### PR DESCRIPTION
**Pull request by miyamotoh**
This PR refactors the TF modules under `data/data/powervs` into 2 "stages," called "cluster" and "post-install." Stages directly correspond to `terraform apply`, and defining 2 stages means it'll run twice, once to build a cluster, then twice to do necessary cleanup (eg. dropping port 22 from LB). Chose the name 'cluster," as it's used by most other platforms. "Post-install" stage is unique to us, and actually "post-bootstrap" (if only closing port 22 on LB), but I figure there are a few more, and thus went for a more generic name.

With this PR merged, the `bootstrap_ip` and `control_plane_ips` will become available for `gather bootstrap` command, as I verified like below;
```
===== immense1:~/git/powervs-ipi (tf-output 20:17:35) =========================                                   
# bin/openshift-install gather bootstrap --dir ocp-test/                                                          
INFO Pulling debug logs from the bootstrap machine                                                                
INFO Bootstrap gather logs captured here "/root/git/powervs-ipi/ocp-test/log-bundle-20211117201746.tar.gz"        
                                               

===== immense1:~/git/powervs-ipi (tf-output 20:18:47) =========================
# ll ocp-test
total 892
drwxr-x--- 2 root root     50 Nov 17 19:54 auth/
-rw-r----- 1 root root    127 Nov 17 20:16 cluster.tfvars.json
-rw-r--r-- 1 root root 169989 Nov 17 20:18 log-bundle-20211117201746.tar.gz
-rw-r----- 1 root root    168 Nov 17 19:54 metadata.json
-rw-r----- 1 root root      2 Nov 17 20:16 post-install.tfvars.json
-rw-r----- 1 root root 428299 Nov 17 20:16 terraform.cluster.tfstate
-rw-r----- 1 root root    157 Nov 17 20:16 terraform.post-install.tfstate
-rw-r----- 1 root root   1322 Nov 17 19:54 terraform.powervs.auto.tfvars.json
-rw-r----- 1 root root 287249 Nov 17 19:54 terraform.tfvars.json
drwxr-x--- 2 root root     62 Nov 17 19:54 tls/
```

Signed-off-by: Hiro Miyamoto <miyamotoh@us.ibm.com>

### CODE REVIEW

**Comment by mjturek** [comment]
LGTM!

**Comment by clnperez** [comment]
this looks good to me as well. i reaaaaallly want to get @bkhadars's validation PR merged before I merge this, but that's taking a while, so, i'll just make sure you ran all the checks there before i merge yours. honor system @miyamotoh :D

**Comment by miyamotoh** [comment]
Well, I did run the following checks locally, and nothing was printed as problem for the files I touched in this PR. I think I'm good. 🙂 
```
# IS_CONTAINER=FALSE hack/go-fmt.sh . 
# IS_CONTAINER=FALSE hack/verify-codegen.sh
# IS_CONTAINER=FALSE ./hack/go-lint.sh -min_confidence 0.3 $(go list -f '{{.ImportPath }}' ./...)
# IS_CONTAINER=FALSE hack/go-vet.sh ./...
# go test ./pkg/...
```

**Pull request merged**
