### PR TITLE
Patchset: add remaining assets for ipi

### PR DESCRIPTION
**Pull request by clnperez**
This is enough for testing for now. 

A few todos:
- Retrieve user account details and ensure the plan is not `lite`
- Add any extra validations steps aside from just account validation
- Rework the validation to use the input from the install-config.yaml instead of only env vars

### CODE REVIEW

**Comment by clnperez** [comment]
@mkumatag @bpradipt 

any comments on the TODOs? I'll follow up on any suggestions in an add'l PR if that's okay. This is to get us a little farther so that @mjturek can test the TF initialization using what we have so far.

**Comment by bpradipt** [comment]
> @mkumatag @bpradipt
> 
> any comments on the TODOs? I'll follow up on any suggestions in an add'l PR if that's okay. This is to get us a little farther so that @mjturek can test the TF initialization using what we have so far.

The TODOs makes sense. I would go even further and say that the user account requirements w.r.to having paid account can be mandated as prereqs in the first phase.

**Review by bpradipt — APPROVED** [review]
/lgtm

**Review by mkumatag — APPROVED** [review]
lgtm

we definitely revisit the code for creating a session, some of the open questions:
1. do we support APIKEY auth because most of the time use will be hesitant to use the password while logging in
2. API KEY is the only way to authenticate and run via tf, so wondering how are we bridging the gap for that.
3. machine-api-provider also depends on the APIKEY

**Comment by clnperez** [comment]
@mkumatag yah i've got the apikey bits in another branch. i can submit a pr for that and we can discuss further.

@bpradipt I agree with:
> I would go even further and say that the user account requirements w.r.to having paid account can be mandated as prereqs in the first phase.

Easy enough to fail & exit if the account is `lite` (as long as that's something we can query using the apis)

**Pull request merged**
