### PR TITLE
Set `powervs_ssh_key` using value in install-config.yaml

### PR DESCRIPTION
**Pull request by mjturek**

### CODE REVIEW

**Comment by mjturek** [comment]
I don't believe this will be required once machine config is working properly - but I could be wrong

**Review by mkumatag — CHANGES_REQUESTED** [review]
Let's remove the default value from the tf as well.

**Comment by mjturek** [comment]
> Let's remove the default value from the tf as well.

done!

**Comment by mkumatag** [comment]
> > Let's remove the default value from the tf as well.
> 
> done!

As a quick check can you run one round of test with supplying any sshkey in the install-config.yaml and see how it behaves.?

**Comment by mjturek** [comment]
> > > Let's remove the default value from the tf as well.
> > 
> > 
> > done!
> 
> As a quick check can you run one round of test with supplying any sshkey in the install-config.yaml and see how it behaves.?

Just ran it. It sets `powervs_ssh_key` to "" and everything seems to still create fine. I think this is the right behavior.

There is still a key in the ignition file but I believe that's generated by the installer?

**Comment by mkumatag** [comment]
> > > > Let's remove the default value from the tf as well.
> > > 
> > > 
> > > done!
> > 
> > 
> > As a quick check can you run one round of test with supplying any sshkey in the install-config.yaml and see how it behaves.?
> 
> Just ran it. It sets `powervs_ssh_key` to "" and everything seems to still create fine. I think this is the right behavior.
> 
> There is still a key in the ignition file but I believe that's generated by the installer?

may be, lets merge this one right away,

**Review by mkumatag — APPROVED** [review]
lgtm

**Comment by mjturek** [comment]
@mkumatag may have spoken too soon, ibm_pi_key doesn't like empty strings
```
ERROR
ERROR Error: Failed to create the key failed to Create PI Key rdr-ipi-mjturek-7cz7t-key with error [POST /pcloud/v1/tenants/{tenant_id}/sshkeys][400] pcloudTenantsSshkeysPostBadRequest  &{Code:0 Description:bad request: rdr-ipi-mjturek-7cz7t-key sshkey is invalid; please enter a valid ssh RSA key: ssh: no key found Error:bad request Message:}
ERROR
ERROR   on ../../../../../tmp/openshift-install--054270139/main.tf line 15, in resource "ibm_pi_key" "cluster_key":
ERROR   15: resource "ibm_pi_key" "cluster_key" {
ERROR
ERROR
ERROR
ERROR Error: timeout while waiting for state to become 'done, ' (last state: 'provisioning', timeout: 30m0s)
ERROR
ERROR   on ../../../../../tmp/openshift-install--054270139/loadbalancer/alb.tf line 16, in resource "ibm_is_lb" "load_balancer_int":
ERROR   16: resource "ibm_is_lb" "load_balancer_int" {
ERROR
ERROR
FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
```

**Comment by mkumatag** [comment]
> @mkumatag may have spoken too soon, ibm_pi_key doesn't like empty strings
> 
> ```
> ERROR
> ERROR Error: Failed to create the key failed to Create PI Key rdr-ipi-mjturek-7cz7t-key with error [POST /pcloud/v1/tenants/{tenant_id}/sshkeys][400] pcloudTenantsSshkeysPostBadRequest  &{Code:0 Description:bad request: rdr-ipi-mjturek-7cz7t-key sshkey is invalid; please enter a valid ssh RSA key: ssh: no key found Error:bad request Message:}
> ERROR
> ERROR   on ../../../../../tmp/openshift-install--054270139/main.tf line 15, in resource "ibm_pi_key" "cluster_key":
> ERROR   15: resource "ibm_pi_key" "cluster_key" {
> ERROR
> ERROR
> ERROR
> ERROR Error: timeout while waiting for state to become 'done, ' (last state: 'provisioning', timeout: 30m0s)
> ERROR
> ERROR   on ../../../../../tmp/openshift-install--054270139/loadbalancer/alb.tf line 16, in resource "ibm_is_lb" "load_balancer_int":
> ERROR   16: resource "ibm_is_lb" "load_balancer_int" {
> ERROR
> ERROR
> FATAL failed to fetch Cluster: failed to generate asset "Cluster": failed to create cluster: failed to apply Terraform: failed to complete the change
> ```

This is what I was wondering!

**Comment by mjturek** [comment]
Should we still merge this? In the end I don't think we want to control the SSH key here but it's currently useful. We can discuss at tomorrow's scrum as well.

**Comment by mkumatag** [comment]
> Should we still merge this? In the end I don't think we want to control the SSH key here but it's currently useful. We can discuss at tomorrow's scrum as well.

I don't mind, @clnperez @bpradipt wdys?

**Comment by clnperez** [comment]
i'm still not clear on what this gets us. didn't get time to chat with mike today before his day ended. what consumes this key and how?

**Comment by mjturek** [comment]
@clnperez currently we consume `powervs_ssh_key` [here](https://github.com/openshift-powervs/installer/blob/add-ipi/data/data/powervs/main.tf#L18) to create a key in powervs. This key gets referenced in the bootstrap and master blocks. Basically this adds the key specified in the install-config via terraform.

I believe eventually we won't want to do this, as other providers inject keys in other ways, but since it's something we still do this seems like the best way to do it.

**Comment by clnperez** [comment]
alrighty, so i think we can merge this, *but* it's not needed for the cluster bringup or node access. summarizing our slack chat here: the ssh keys are added via ignition. since the ssh key is a required param by the tf provider, we might as well pass in a sane value. it could come in handy for debug if something goes sideways. 

one request for this pr: update the description for the var stating that it's mandatory for the tf provider

**Comment by mjturek** [comment]
> alrighty, so i think we can merge this, _but_ it's not needed for the cluster bringup or node access. summarizing our slack chat here: the ssh keys are added via ignition. since the ssh key is a required param by the tf provider, we might as well pass in a sane value. it could come in handy for debug if something goes sideways.
> 
> one request for this pr: update the description for the var stating that it's mandatory for the tf provider

Done!

**Comment by clnperez** [comment]
thanks. LTGM

**Pull request merged**
