### PR TITLE
Opening ports 443 and 80

### PR DESCRIPTION
**Pull request by 23TNC**
Signed-off-by: wolf <cory.klokman@ibm.com>

### CODE REVIEW

**Comment by mkumatag** [comment]
Why are we exposing these ports?

**Comment by clnperez** [comment]
@mkumatag -- so that we can access the console? is there another way we should do this?

**Comment by mkumatag** [comment]
> @mkumatag -- so that we can access the console? is there another way we should do this?

Usually console is exposed via openshift routes backed by ingress operator, @Karthik-K-N's work should create all those default lb, security groups, etc..

**Comment by clnperez** [comment]
i see! thanks. Is that already in the works? I see the DNS PR but not this one yet.

**Comment by mkumatag** [comment]
> i see! thanks. Is that already in the works? I see the DNS PR but not this one yet.

this will be part of cloud-manager code, @Karthik-K-N can update more on this

**Comment by 23TNC** [comment]
Should I close this then?

**Comment by clnperez** [comment]
Yah. Sorry @23TNC . I didn't realize that's how this worked

**Pull request closed without merging**
